# Generated by Django 3.2.18 on 2023-02-22 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230221_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='disease',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizer_per_meter',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='has_plant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='health',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='insects_per_meter',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='number_or_stems',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_cohesity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_moisture_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
