# Generated by Django 3.2.18 on 2023-02-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_plant_garden_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='garden_id',
            field=models.CharField(max_length=255),
        ),
    ]
